// <auto-generated />
using System;
using AgiCredAju79.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgiCredAju79.Migrations
{
    [DbContext(typeof(DbContextMariaDB))]
    [Migration("20251030202524_create_pagamento")]
    partial class create_pagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.NotaEmprestimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Armotizado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDePromessaDePagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoAcordo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoUltimoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Indicacao")
                        .HasColumnType("longtext");

                    b.Property<int?>("JuroMensalPorcentagem")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosPagosTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ListaParcelasPagas")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeEmprestimo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorDoEmprestimo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("NotaEmprestimo");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comprovante")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desconto")
                        .HasColumnType("longtext");

                    b.Property<string>("DescontoDescricao")
                        .HasColumnType("longtext");

                    b.Property<long>("EmprestimoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
