// <auto-generated />
using System;
using AgiCredAju79.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgiCredAju79.Migrations
{
    [DbContext(typeof(DbContextMariaDB))]
    [Migration("20251204212824_create_cadastro_full")]
    partial class create_cadastro_full
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.Cadastro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("CPFStatus")
                        .HasColumnType("longtext");

                    b.Property<long?>("CadastroIdIndicacao")
                        .HasColumnType("bigint");

                    b.Property<long?>("CadastroIdIndicacaoAvalista")
                        .HasColumnType("bigint");

                    b.Property<string>("CadastroNumeroDeContatoIdPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("CadastroNumeroDeContatoStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataDeNascimentoStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoIdPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("EnderecoStatus")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("LimiteDeSolicitacaoDeEmprestimoValor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.CadastroEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BairroOuDistrito")
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<long>("CadastroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("ComprovanteDeEnderecoPATH")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkDoMapa")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDeIdentificacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("CadastroEndereco");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.CadastroNumeroDeContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CadastroId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeDeIdentificacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("CadastroNumeroDeContato");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.Emprestimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<long>("CadastroId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CadastroIndicacaoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CadastroResponsavelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CelularPrincipal")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDePromessaDePagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoAcordo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoUltimoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DiaDoPagamento")
                        .HasColumnType("int");

                    b.Property<int?>("JuroMensalPorcentagem")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeEmprestimo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorDoEmprestimo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.NotaEmprestimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Armotizado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataDePromessaDePagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoAcordo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoUltimoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Indicacao")
                        .HasColumnType("longtext");

                    b.Property<int?>("JuroMensalPorcentagem")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosPagosTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ListaParcelasPagas")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeEmprestimo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorDoEmprestimo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("NotaEmprestimo");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.Pagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comprovante")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DescontoDescricao")
                        .HasColumnType("longtext");

                    b.Property<long>("EmprestimoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.CadastroEndereco", b =>
                {
                    b.HasOne("AgiCredAju79.Repositories.Models.Cadastro", null)
                        .WithMany("CadastroEndereco")
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.CadastroNumeroDeContato", b =>
                {
                    b.HasOne("AgiCredAju79.Repositories.Models.Cadastro", null)
                        .WithMany("CadastroNumeroDeContato")
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgiCredAju79.Repositories.Models.Cadastro", b =>
                {
                    b.Navigation("CadastroEndereco");

                    b.Navigation("CadastroNumeroDeContato");
                });
#pragma warning restore 612, 618
        }
    }
}
